---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: activemq-volume1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/u01/platform/activemq/broker1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: activemq-volume2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/u01/platform/activemq/broker2"

