-
  name: Install docker on servers
  hosts: tupil
  tasks:

     -  name: install yum utils
        yum: 
          name: yum-utils
          state: latest

     -  name: install device-mappers
        yum:
           name: device-mapper-persistent-data
           state: latest

     -  name: install lvm2 
        yum:
           name: lvm2
           state: latest

     -  name: add docker repo
        get_url:
           url: https://download.docker.com/linux/centos/docker-ce.repo
           dest: /etc/yum.repos.d/docker-ce.repo
        become: yes

     -  name: install docker
        package:
           name: docker-ce-18.03.1.ce-1.el7.centos
           state: present
        become: yes
  
     -  name: start docker service
        service:
          name: docker
          state: started
        become: yes

     -  name: copy daemon.json file
        copy:
         src: /opt/k8s_lakshay/files/daemon.json
         dest: /etc/docker/daemon.json 
   
     -  name: create docker.service.d directory
        file:
          path: /etc/systemd/system/docker.service.d
          state: directory
 
     -  name: copy docker.conf file
        copy: 
         src: /opt/k8s_lakshay/files/docker.conf
         dest: /etc/systemd/system/docker.service.d/docker.conf
    
     -  name: daemon reload
        command: systemctl daemon-reload
   
     -  name: restart docker
        service: 
          name: docker
          state: restarted
          enabled: yes

     -  name: check docker status
        command: service docker status

     -  name: do host entry
        blockinfile:
           path : /etc/hosts
           block: |
             10.151.32.160 harborreg.sterlitetech-software.com
             192.168.11.158 gitlab.sterlitetech-software.com
             192.168.11.158 jfrog.sterlite.com          
