---
-  name: Install k8s on all servers
   hosts: slave
   vars_files:
   - /opt/k8s_lakshay/env_variables
   tasks:
      -  name: copy k8s.conf file to servers
         copy:
           src: /opt/k8s_lakshay/files/k8s.conf
           dest: /etc/sysctl.d/k8s.conf

      -  name: execute sysctl --system command
         command: sysctl --system

      -  name: copy kubernetes.repo file
         copy:
           src: /opt/k8s_lakshay/files/kubernetes.repo
           dest: /etc/yum.repos.d/kubernetes.repo

      -  name: make changes in sysctl.conf
         command: sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf

      -  name: executing sysctl on sysctl.conf
         command: sysctl -p /etc/sysctl.conf

      -  name: disable swap on all nodes
         shell : swapoff -a

      -  name: disable selinux on nodes
         command: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

      -  name: install packages on nodes
         yum:
           name: "{{ item }}"
           state: present
         with_items: "{{ packages }}"
               

      -  name: make net.d directory
         file:
           path: /etc/cni/net.d
           state: directory

      -  name: copy 10-weave.conf file
         copy:
           src: /opt/k8s_lakshay/files/10-weave.conflist
           dest: /etc/cni/net.d/10-weave.conflist
      -  name: reload deamon
         command: systemctl daemon-reload

      -  name: restart kubelet service
         service:
           name: kubelet
           state: restarted
